### ISSUE TITLE
>Ensures raw binary string length returned

### ISSUE THREAD

**Issue by divinity76** [indigophp/hash-compat#5]
just what have you been smoking? strlen() `always` counts number of bytes, why did you even consider mb_strlen here? talking about this code 
```php
    defined('USE_MB_STRING') or define('USE_MB_STRING', function_exists('mb_strlen'));
...
        // Ensures raw binary string length returned
        $strlen = function($string) {
            if (USE_MB_STRING) {
                return mb_strlen($string, '8bit');
            }
            return strlen($string);
        };

```
- all that can be thrown away, just stick to strlen(), it always returns number of bytes, unless you want to be compatible with (the abandoned, never-released) PHP6...

edit: see https://github.com/indigophp/hash-compat/pull/6

**Comment by sagikazarmark** [comment]
Thanks for bringing this up. You are absolutely right, that `strlen` would do the job as well.

However, when `mbstring` is installed, `strlen` cannot be trusted anymore because of the [mbstring function overloading](http://php.net/manual/en/mbstring.overload.php). Since this is a PHP ini setting, I chose falling back to `mb_strlen` instead of guessing whether overloading is enabled or not.

If you are certain, that you don't have that setting enabled, you can define the `USE_MB_STRING` constant with `false` value, as `mb_strlen` is admittedly way slower than `strlen`. Other than that, I don't see any valid reason against the code above.

**Comment by divinity76** [comment]
wow, i didn't know about that `feature` at all. thanks for explaining!

globally overloading core functions to do something completely different?


![Image](http://starecat.com/content/wp-content/uploads/what-could-possibly-go-wrong-cutting-fail.jpg)
